apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-tsigkey
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
data:
  tsigkey: {{ $.Values.tsigkey }}
