apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-1
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: issuer
    cert-manager.io/issuer-kind: ClusterIssuer
spec:
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: {{ .Release.Name }}-tls
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}
            port:
              number: 80
